'use strict';

module.exports = {
    "WRONG_SERVER": "WRONG_SERVER",
    "WRONG_PASSWORD": "WRONG_PASSWORD",
    "WRONG_USERNAME": "WRONG_USERNAME",
    "ERROR_IN_DATABASE": "ERROR_IN_DATABASE",
    "COULD_NOT_FIND_USER": "COULD_NOT_FIND_USER",
};
